name: SyncToOSS

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up ossutil
      run: |
        # 下载 ossutil
        curl -o ossutil64 http://gosspublic.alicdn.com/ossutil/1.6.7/ossutil64
        chmod +x ossutil64
        
        # 创建 .local/bin 目录并移动 ossutil
        mkdir -p $HOME/.local/bin
        mv ossutil64 $HOME/.local/bin/ossutil
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Configure ossutil
      run: |
        ossutil config -e oss-cn-hongkong.aliyuncs.com -i ${{ secrets.ACCESS_KEY_ID }} -k ${{ secrets.ACCESS_KEY_SECRET }} -L CH

    - name: Deploy To OSS
      run: |
        ossutil cp . oss://gaoyi1creditwebpage/ --recursive --exclude ".git/*" --exclude ".git"
