name: Deploy to Aliyun OSS

on:
  push:
    branches:
      - main  # 当推送到 main 分支时自动触发
  workflow_dispatch:  # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install OSS CLI
        run: |
          curl -o ossutil.zip https://gosspublic.alicdn.com/ossutil/1.7.19/ossutil-v1.7.19-linux-amd64.zip  # 下载最新的 Linux 版本
          unzip ossutil.zip  # 解压到当前目录
          sudo mv ossutil-v1.7.19-linux-amd64/ossutil /usr/local/bin/ossutil  # 移动到正确的位置
          sudo chmod 755 /usr/local/bin/ossutil

      - name: Verify OSS CLI Installation
        run: |
          ossutil help  # 使用 help 命令检查安装是否成功

      - name: Configure OSS CLI
        run: |
          ossutil config -e ${{ secrets.OSS_REGION }} -i ${{ secrets.ALIYUN_ACCESS_KEY_ID }} -k ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}

      - name: Debug OSS Config
        run: |
          echo "OSS_REGION: ${{ secrets.OSS_REGION }}"
          echo "OSS_BUCKET: ${{ secrets.OSS_BUCKET }}"

      - name: List OSS Bucket
        run: |
          ossutil ls oss://${{ secrets.OSS_BUCKET }}/  # 列出存储桶中的文件

      - name: Sync files to OSS
        run: |
          ossutil sync ./ oss://${{ secrets.OSS_BUCKET }}/ --delete  # 使用 sync 命令同步文件
