name: Deploy to Aliyun OSS

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install OSS CLI
        run: |
          curl -o ossutil.zip https://gosspublic.alicdn.com/ossutil/1.7.0/ossutil64.zip
          unzip ossutil.zip
          sudo mv ossutil64 /usr/local/bin/ossutil
          chmod 755 /usr/local/bin/ossutil

      - name: Configure OSS CLI
        run: |
          ossutil config -e ${{ secrets.OSS_REGION }} -i ${{ secrets.ALIYUN_ACCESS_KEY_ID }} -k ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}

      - name: Sync files to OSS
        run: |
          ossutil rsync ./ oss://${{ secrets.OSS_BUCKET }}/ --delete
